version: '3'
services:
  editor:
    container_name: ${PROJECT_NAME:-testProject}_swagger-editor
    image: 'swaggerapi/swagger-editor'
    volumes:
      - ./api/api.yaml:/tmp/swagger.yaml
      - ./api/data/:/tmp/data/
    ports:
      - 8100:8080
    environment:
      SWAGGER_FILE: "/tmp/swagger.yaml"

  ui:
    container_name: ${PROJECT_NAME:-testProject}_swagger-ui
    image: 'swaggerapi/swagger-ui'
    volumes:
      - ./api:/usr/share/nginx/html/docs
    ports:
      - 8200:8080
    environment:
      URL: "./docs/api.yaml"
