version: '3.7'

services:
  master:
    image: locustio/locust
    container_name: ${PROJECT_NAME}_locust_master
    ports:
     - "${LOCUST_PORT}:8089"
    volumes:
      - ./loadTest/locust:/mnt/locust
      - ./loadTest/log:/home/locust/log # ログ出力
    # command: -f /mnt/locust/locustfile.py --master -H ${LOCUST_TEST_TARGET_HOST}
    command: -f /mnt/locust/locustfile.py --master -H ${LOCUST_TEST_TARGET_HOST} --csv=log/test --csv-full-history --logfile=log/test.log
    environment:
      TZ: "Asia/Tokyo"
    networks:
      default:

  worker:
    image: locustio/locust
    # container_name: ${PROJECT_NAME}_locust_woker # wokerごとに採番する必要がある為固定で名前をつけない
    volumes:
      - ./loadTest/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    environment:
      TZ: "Asia/Tokyo"
    networks:
      default:

networks:
  default:
    external: true
    name: ${NETWORK_NAME}
