version: '3.7'

services:
  jenkins-master:
    container_name: ${PROJECT_NAME}-jenkins-master
    image: jenkins/jenkins:latest
    volumes:
      - ./jenkins/home:/var/jenkins_home
      - ~/.aws:/var/jenkins_home/.aws:ro # read only
      - ~/.ssh:/var/jenkins_home/.ssh:ro # read only
      - ./jenkins/scripts:/usr/local/scripts
    ports:
      - "${JENKINS_CLIENT_PORT:-8080}:8080"
      - "${JENKINS_SERVER_PORT:-50000}:50000"
    environment:
      TZ: "Asia/Tokyo"
